export const ADMIN_ORGANIZATION_REQUEST_STATUS_FILTERS = [
  'PENDING',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
] as const;

export const ADMIN_ORGANIZATION_STATUS_FILTERS = [
  'ACTIVE',
  'SUSPENDED',
  'ARCHIVED',
  'DELETED',
] as const;
