ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALENDAR_EVENT_LINKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CALENDAR_EVENT_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMBER_ADDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMBER_REMOVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORGANIZATION_REQUEST_CREATED';

ALTER TABLE "notification_preferences"
  ADD COLUMN IF NOT EXISTS "organization_updates_enabled" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "notification_preferences"
  ADD COLUMN IF NOT EXISTS "time_zone" VARCHAR(64);
